Updated the feature branch of dr_hook to be functional with vn6 of WW3 and any other changes that have been made since first instance of drhook.

diff --git a/model/bin/link.tmpl b/model/bin/link.tmpl
--- a/model/bin/link.tmpl
+++ b/model/bin/link.tmpl
@@ -132,6 +132,17 @@
       libs="$libs $METIS_PATH/lib/libparmetis.a $METIS_PATH/lib/libmetis.a"
     fi
   fi
+ 
+  # drhook library dir
+  if [ "$hook_mod" = 'yes' ]
+  then
+    if [ -z "$HOOK_LIBDIR" ]
+    then
+      echo "ERROR: \$HOOK_LIBDIR not defined"; echo ' '
+      exit 1
+    fi
+    libs="$libs -L$HOOK_LIBDIR -ldrhook"
+  fi
 
   # OMP support
   if [ "$omp_mod" = 'yes' ] ; then
