Remove linking to old WAVELIB library
Currently the only file required in use is the cmps_all routine, which
is self contained and used exclusively by ww3_mopp. I think it is more
straightforward to just include this file within the ukmo_operutils suite

diff --git a/model/bin/link.tmpl b/model/bin/link.tmpl
--- a/model/bin/link.tmpl
+++ b/model/bin/link.tmpl
@@ -149,14 +149,14 @@
     opt="$opt <optomp>"
   fi
   
-  # COEX library support (UK Met Office only)
-  if [ "$prog" = 'ww3_mopp' ]; then
-    if [[ -z ${WAVELIB} ]]; then
-	  echo "ERROR: WAVELIB environment variable not set"
-	  exit 1
-	fi
-    libs="$libs -L${WAVELIB} -lcoex"
-  fi
+#  # COEX library support (UK Met Office only) -- no longer needed
+#  if [ "$prog" = 'ww3_mopp' ]; then
+#    if [[ -z ${WAVELIB} ]]; then
+#	  echo "ERROR: WAVELIB environment variable not set"
+#	  exit 1
+#	fi
+#    libs="$libs -L${WAVELIB} -lcoex"
+#  fi
 
   opt="$opt $EXTRA_LINK_OPTIONS"
 
