Add ukmo-operutils support to cmake build

diff --git a/model/bin/link.tmpl b/model/bin/link.tmpl
--- a/model/bin/link.tmpl
+++ b/model/bin/link.tmpl
@@ -148,6 +148,15 @@
   if [ "$omp_mod" = 'yes' ] ; then
     opt="$opt <optomp>"
   fi
+  
+  # COEX library support (UK Met Office only)
+  if [ "$prog" = 'ww3_mopp' ]; then
+    if [[ -z ${WAVELIB} ]]; then
+	  echo "ERROR: WAVELIB environment variable not set"
+	  exit 1
+	fi
+    libs="$libs -L${WAVELIB} -lcoex"
+  fi
 
   opt="$opt $EXTRA_LINK_OPTIONS"
 
